name: Build and Publish Debian Image

on:
  push:
    branches: [ "main" ]
    paths:
        - configs/Debian/Dockerfile
        - .github/workflows/build-debian-image.yml
  workflow_dispatch:

env:
  IMAGE_NAME: HamRadioUtils

jobs:
  debian-image-ghcr:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_TOKEN }}

    - name: Build and push image
      id: push-ghcr
      uses: docker/build-push-action@v6.9.0
      with:
        context: configs/Debian
        push: true
        tags: ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
  
    - name: Attest pushed image
      uses: actions/attest-build-provenance@v1
      id: attest
      with:
        subject-name: ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}
        subject-digest: ${{ steps.push-ghcr.outputs.digest }}
        push-to-registry: true

